export const ROUTES = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAILS: '/products/:id',
  BUNDLES: '/bundles',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDER_SUCCESS: '/order-success/:orderId',
  ORDERS: '/orders',
  ORDER_TRACKING: '/orders/:orderId/tracking',
  PROFILE: '/profile',
  WISHLIST: '/wishlist',
  LOGIN: '/login',
  REGISTER: '/register',
  CREDIT_SIMULATOR: '/credit-simulator',
  MY_CREDITS: '/my-credits',
  ADMIN: '/admin',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_CREDITS: '/admin/credits',
} as const;
